[package]
name = "bsp-explorer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.27"
wgpu = "0.16"
env_logger = "0.10"
log = "0.4"
pollster = "0.3"
bytemuck = { version = "1.12", features = ["derive"] }
gltf = "1.0"
puffin = "0.16"
crate = "0.0.2"
imgui = "0.11"
imgui-wgpu = "0.23"
imgui-winit-support = "0.11"
async-trait = "0.1"
glam = { version = "0.24.1", features = [
	"bytemuck",
] } #https://docs.rs/glam/latest/glam/
flagset = "0.4.3"
num-traits = "0.2.16"
num-derive = "0.4.0"
