[package]
name = "bsp-explorer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.27"
wgpu = "0.16"
env_logger = "0.10"
log = "0.4"
pollster = "0.3"
bytemuck = { version = "1.13", features = ["derive", "extern_crate_alloc"] }
puffin = "0.16"
crate = "0.0.2"
imgui = { version = "0.11", features = ["tables-api"] }
imgui-wgpu = "0.23"
imgui-winit-support = "0.11"
async-trait = "0.1"
glam = { version = "0.24.1", features = [
	"bytemuck",
] } #https://docs.rs/glam/latest/glam/
flagset = "0.4.3"
num-traits = "0.2.16"
num-derive = "0.4.0"
stream-unzip = "0.2.1"
rayon = "1.7.0"
bevy_ecs = "0.11.2"
getset = "0.1.2"
