use bytemuck::{Pod, Zeroable};
use flagset::flags;
use num_derive::{FromPrimitive, Zero};
use wgpu::TextureFormat;

#[derive(Copy, Clone, FromPrimitive, Debug)]
#[repr(i32)]
pub enum ImageFormat {
    NONE = -1,
    RGBA8888 = 0,
    ABGR8888,
    RGB888,
    BGR888,
    RGB565,
    I8,
    IA88,
    P8,
    A8,
    RGB888_BLUESCREEN,
    BGR888_BLUESCREEN,
    ARGB8888,
    BGRA8888,
    DXT1,
    DXT3,
    DXT5,
    BGRX8888,
    BGR565,
    BGRX5551,
    BGRA4444,
    DXT1_ONEBITALPHA,
    BGRA5551,
    UV88,
    UVWQ8888,
    RGBA16161616F,
    RGBA16161616,
    UVLX8888,
}
impl ImageFormat {
    pub fn bytes_for_size(&self, width: usize, height: usize) -> usize {
        match self {
            ImageFormat::NONE => todo!(),
            ImageFormat::RGBA8888 => todo!(),
            ImageFormat::ABGR8888 => todo!(),
            ImageFormat::RGB888 => todo!(),
            ImageFormat::BGR888 => todo!(),
            ImageFormat::RGB565 => todo!(),
            ImageFormat::I8 => todo!(),
            ImageFormat::IA88 => todo!(),
            ImageFormat::P8 => todo!(),
            ImageFormat::A8 => todo!(),
            ImageFormat::RGB888_BLUESCREEN => todo!(),
            ImageFormat::BGR888_BLUESCREEN => todo!(),
            ImageFormat::ARGB8888 => todo!(),
            ImageFormat::BGRA8888 => todo!(),
            ImageFormat::DXT1 => width * height * 8 / 16,
            ImageFormat::DXT3 => todo!(),
            ImageFormat::DXT5 => todo!(),
            ImageFormat::BGRX8888 => todo!(),
            ImageFormat::BGR565 => todo!(),
            ImageFormat::BGRX5551 => todo!(),
            ImageFormat::BGRA4444 => todo!(),
            ImageFormat::DXT1_ONEBITALPHA => todo!(),
            ImageFormat::BGRA5551 => todo!(),
            ImageFormat::UV88 => todo!(),
            ImageFormat::UVWQ8888 => todo!(),
            ImageFormat::RGBA16161616F => todo!(),
            ImageFormat::RGBA16161616 => todo!(),
            ImageFormat::UVLX8888 => todo!(),
        }
    }
}
impl TryFrom<ImageFormat> for wgpu::TextureFormat {
    type Error = ();

    fn try_from(value: ImageFormat) -> Result<Self, Self::Error> {
        match value {
            ImageFormat::NONE => Err(()),
            ImageFormat::RGBA8888 => Ok(wgpu::TextureFormat::Rgba8Uint),
            ImageFormat::ABGR8888 => todo!(),
            ImageFormat::RGB888 => todo!(),
            ImageFormat::BGR888 => todo!(),
            ImageFormat::RGB565 => todo!(),
            ImageFormat::I8 => todo!(),
            ImageFormat::IA88 => todo!(),
            ImageFormat::P8 => todo!(),
            ImageFormat::A8 => todo!(),
            ImageFormat::RGB888_BLUESCREEN => todo!(),
            ImageFormat::BGR888_BLUESCREEN => todo!(),
            ImageFormat::ARGB8888 => todo!(),
            ImageFormat::BGRA8888 => todo!(),
            ImageFormat::DXT1 => Ok(wgpu::TextureFormat::Bc1RgbaUnormSrgb),
            ImageFormat::DXT3 => Ok(wgpu::TextureFormat::Bc2RgbaUnormSrgb),
            ImageFormat::DXT5 => Ok(wgpu::TextureFormat::Bc3RgbaUnormSrgb),
            ImageFormat::BGRX8888 => todo!(),
            ImageFormat::BGR565 => todo!(),
            ImageFormat::BGRX5551 => todo!(),
            ImageFormat::BGRA4444 => todo!(),
            ImageFormat::DXT1_ONEBITALPHA => todo!(),
            ImageFormat::BGRA5551 => todo!(),
            ImageFormat::UV88 => todo!(),
            ImageFormat::UVWQ8888 => todo!(),
            ImageFormat::RGBA16161616F => todo!(),
            ImageFormat::RGBA16161616 => todo!(),
            ImageFormat::UVLX8888 => todo!(),
        }
    }
}

unsafe impl Zeroable for ImageFormat {}
unsafe impl Pod for ImageFormat {}

flags! {
    #[repr(u32)]
    pub enum CompiledVtfFlags: u32 {
        // Flags from the *.txt config file
        TEXTUREFLAGS_POINTSAMPLE = 0x00000001,
        TEXTUREFLAGS_TRILINEAR = 0x00000002,
        TEXTUREFLAGS_CLAMPS = 0x00000004,
        TEXTUREFLAGS_CLAMPT = 0x00000008,
        TEXTUREFLAGS_ANISOTROPIC = 0x00000010,
        TEXTUREFLAGS_HINT_DXT5 = 0x00000020,
        TEXTUREFLAGS_PWL_CORRECTED = 0x00000040,
        TEXTUREFLAGS_NORMAL = 0x00000080,
        TEXTUREFLAGS_NOMIP = 0x00000100,
        TEXTUREFLAGS_NOLOD = 0x00000200,
        TEXTUREFLAGS_ALL_MIPS = 0x00000400,
        TEXTUREFLAGS_PROCEDURAL = 0x00000800,

        // These are automatically generated by vtex from the texture data.
        TEXTUREFLAGS_ONEBITALPHA = 0x00001000,
        TEXTUREFLAGS_EIGHTBITALPHA = 0x00002000,

        // Newer flags from the *.txt config file
        TEXTUREFLAGS_ENVMAP = 0x00004000,
        TEXTUREFLAGS_RENDERTARGET = 0x00008000,
        TEXTUREFLAGS_DEPTHRENDERTARGET = 0x00010000,
        TEXTUREFLAGS_NODEBUGOVERRIDE = 0x00020000,
        TEXTUREFLAGS_SINGLECOPY	= 0x00040000,
        TEXTUREFLAGS_PRE_SRGB = 0x00080000,

        TEXTUREFLAGS_UNUSED_00100000 = 0x00100000,
        TEXTUREFLAGS_UNUSED_00200000 = 0x00200000,
        TEXTUREFLAGS_UNUSED_00400000 = 0x00400000,

        TEXTUREFLAGS_NODEPTHBUFFER = 0x00800000,

        TEXTUREFLAGS_UNUSED_01000000 = 0x01000000,

        TEXTUREFLAGS_CLAMPU = 0x02000000,
        TEXTUREFLAGS_VERTEXTEXTURE = 0x04000000,
        TEXTUREFLAGS_SSBUMP = 0x08000000,

        TEXTUREFLAGS_UNUSED_10000000 = 0x10000000,

        TEXTUREFLAGS_BORDER = 0x20000000,

        TEXTUREFLAGS_UNUSED_40000000 = 0x40000000,
        TEXTUREFLAGS_UNUSED_80000000 = 0x80000000,
    }
}
unsafe impl Zeroable for CompiledVtfFlags {}
unsafe impl Pod for CompiledVtfFlags {}
