[build]
rustflags = ["--cfg=web_sys_unstable_apis"]

# for Linux
# [target.x86_64-unknown-linux-gnu]
# linker = "clang"
# rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold"]


# for Windows
[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
